# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.best_combination <- function(Rw, Rf, Rv, loops, prod) {
    .Call('_SmallGroupNetwork_best_combination', PACKAGE = 'SmallGroupNetwork', Rw, Rf, Rv, loops, prod)
}

test_rcpp <- function() {
    invisible(.Call('_SmallGroupNetwork_test_rcpp', PACKAGE = 'SmallGroupNetwork'))
}

